const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const store={get(k,f){try{return JSON.parse(localStorage.getItem('myworld_'+k))??f}catch{return f}},set(k,v){localStorage.setItem('myworld_'+k,JSON.stringify(v))}};
const defaults={goals:[{name:'Финансовая стабильность',progress:60},{name:'Развиваться в бариста',progress:50},{name:'Собрать новый ПК',progress:33},{name:'Путешествовать',progress:0},{name:'Быть в форме',progress:67}],operations:[{title:'Зарплата',amount:3250,type:'income',date:'Сегодня'},{title:'Расходы',amount:820,type:'expense',date:'Сегодня'}],balance:48320,notes:''};
let data=store.get('data',defaults); let calDate=new Date();
function save(){store.set('data',data)}
function money(n){return new Intl.NumberFormat('ru-RU').format(n)+' ₽'}
function renderGoals(){const html=data.goals.map(g=>`<div class="goal-line"><span class="dot"></span><div><div class="goal-name">${escapeHtml(g.name)}</div><div class="progress"><i style="width:${g.progress}%"></i></div></div><b>${g.progress}%</b></div>`).join(''); $('#goalPreview').innerHTML=html; $('#goalsPage').innerHTML=data.goals.map((g,i)=>`<article class="card goal-full"><div class="goal-top"><h3>${escapeHtml(g.name)}</h3><b>${g.progress}%</b></div><div class="progress"><i style="width:${g.progress}%"></i></div><div style="display:flex;gap:8px;margin-top:14px"><button class="outline-btn" onclick="changeGoal(${i},-10)">−10%</button><button class="outline-btn" onclick="changeGoal(${i},10)">+10%</button></div></article>`).join('')}
function changeGoal(i,n){data.goals[i].progress=Math.max(0,Math.min(100,data.goals[i].progress+n));save();renderGoals()}
function renderOperations(){let inc=data.operations.filter(x=>x.type==='income').reduce((a,x)=>a+x.amount,0),exp=data.operations.filter(x=>x.type==='expense').reduce((a,x)=>a+x.amount,0);$('#incomePreview').textContent='+ '+money(inc);$('#expensePreview').textContent='− '+money(exp);$('#balancePreview').textContent=money(data.balance);$('#financeBalance').textContent=money(data.balance);$('#operationsList').innerHTML=data.operations.slice(0,10).map((o,i)=>`<div class="operation"><div><b>${escapeHtml(o.title)}</b><small>${o.date}</small></div><b class="${o.type==='income'?'positive':'negative'}">${o.type==='income'?'+':'−'} ${money(o.amount)}</b></div>`).join('')}
function renderClock(){const d=new Date();$('#clock').textContent=d.toLocaleTimeString('ru-RU',{hour:'2-digit',minute:'2-digit'});$('#date').textContent=d.toLocaleDateString('ru-RU',{day:'numeric',month:'long',year:'numeric'});$('#todayLabel').textContent=d.toLocaleDateString('ru-RU',{day:'numeric',month:'long'});$('#todayList').innerHTML=[['☕','Работа','09:00 – 17:00'],['♧','Тренировка','19:00'],['▤','Почитать','21:00'],['▤','Сделать заметки','В любое время']].map(x=>`<div class="today-item"><span>${x[0]}</span><div>${x[1]}<small>Личные планы</small></div><time>${x[2]}</time></div>`).join('')}
function showSection(id){$$('.section').forEach(s=>s.classList.toggle('active-section',s.id===id));$$('[data-section]').forEach(b=>b.classList.toggle('active',b.dataset.section===id));window.scrollTo({top:0,behavior:'smooth'})}
function renderCalendar(){const y=calDate.getFullYear(),m=calDate.getMonth();$('#monthTitle').textContent=calDate.toLocaleDateString('ru-RU',{month:'long',year:'numeric'});const first=new Date(y,m,1);let start=(first.getDay()+6)%7;const days=new Date(y,m+1,0).getDate();let out='';for(let i=0;i<start;i++)out+='<div class="day empty"></div>';for(let d=1;d<=days;d++){const work=[1,3,5,8,10,12,15,17,19,22,24,26].includes(d);const today=new Date();const isToday=d===today.getDate()&&m===today.getMonth()&&y===today.getFullYear();out+=`<button class="day ${work?'work':''} ${isToday?'today':''}" onclick="toggleWork(this)"><span>${d}</span>${work?'<small>Работа</small>':''}</button>`}$('#calendarGrid').innerHTML=out}
function toggleWork(el){el.classList.toggle('work');const s=el.querySelector('small');if(s)s.remove();else el.insertAdjacentHTML('beforeend','<small>Работа</small>')}
function escapeHtml(s){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
$$('[data-section]').forEach(b=>b.addEventListener('click',()=>showSection(b.dataset.section)));$$('[data-section-jump]').forEach(b=>b.addEventListener('click',()=>showSection(b.dataset.sectionJump)));
$('#themeToggle').addEventListener('click',()=>{document.body.classList.toggle('light');store.set('light',document.body.classList.contains('light'))});$('#mobileTheme').addEventListener('click',()=>$('#themeToggle').click());
$('#goalForm').addEventListener('submit',e=>{e.preventDefault();data.goals.push({name:$('#goalName').value,progress:+$('#goalProgress').value||0});$('#goalName').value='';$('#goalProgress').value=0;save();renderGoals()});
let financeType='income';$$('.toggle button').forEach(b=>b.addEventListener('click',()=>{$$('.toggle button').forEach(x=>x.classList.remove('active'));b.classList.add('active');financeType=b.dataset.type}));$('#financeForm').addEventListener('submit',e=>{e.preventDefault();const amount=+$('#financeAmount').value,title=$('#financeTitle').value.trim();if(!amount||!title)return;data.operations.unshift({title,amount,type:financeType,date:'Сегодня'});data.balance+=financeType==='income'?amount:-amount;save();$('#financeAmount').value='';$('#financeTitle').value='';renderOperations()});
$('#notesArea').value=data.notes;$('#notesArea').addEventListener('input',()=>{data.notes=$('#notesArea').value;save();$('#saveState').textContent='Сохранено '+new Date().toLocaleTimeString('ru-RU',{hour:'2-digit',minute:'2-digit'})});$('#clearNotes').addEventListener('click',()=>{data.notes='';$('#notesArea').value='';save();$('#saveState').textContent='Заметка очищена'});
$('#prevMonth').addEventListener('click',()=>{calDate.setMonth(calDate.getMonth()-1);renderCalendar()});$('#nextMonth').addEventListener('click',()=>{calDate.setMonth(calDate.getMonth()+1);renderCalendar()});
if(store.get('light',false))document.body.classList.add('light');renderClock();setInterval(renderClock,1000);renderGoals();renderOperations();renderCalendar();
